name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.13]
    #    go-version: [1.13.x]
    runs-on: ${{ matrix.platform }}
    container: golang:${{ matrix.go-version }}
    
    steps:
    #- name: Set up Go 1.13
    #  uses: actions/setup-go@v1
    #  with:
    #    go-version: ${{ matrix.go-version }}
    #  id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
